name: i9xp_visual_pkg
description: A package to shared visual responsabilities to the project
version: 0.0.1
author: Emanuel Braz
homepage: fastencoding@gmail.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
   - assets/images/
