name: i9xp_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Gerenciamento de estado
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1

  # Widgets utilitários
  mobx_widget: 
    git: https://github.com/emanuel-braz/mobx_widget.git
  
  # Ícones cupertino
  cupertino_icons: ^0.1.2

  # Local visual components package
  i9xp_visual_pkg:
    path: ../i9xp_visual_pkg

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1

flutter:

  uses-material-design: true